config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

  before_destroy :check_if_last_bookmark_for_movie

  private

  def check_if_last_bookmark_for_movie
    throw(:abort) if movie.bookmarks.count == 1
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true

  before_destroy :destroy_associated_bookmarks

  private

  def destroy_associated_bookmarks
    bookmarks.destroy_all
  end
  
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
    # @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully destroyed.'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1 class="text-center mt-4">Delete Bookmark</h1>

<div class="container mt-4">
  <p>Are you sure you want to delete this bookmark?</p>

  <%= link_to 'Back to List', list_path(@list) %>
  <%= link_to 'Delete Bookmark', list_bookmark_path(@list, @bookmark), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/bookmarks/new.html.erb
<h1>Add a movie to your <%= @list.name %> list</h1>

<div class="container mt-4">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, prompt: "Select a movie" %>
    <%= f.submit 'Create Bookmark' %>
  <% end %>

  <%= link_to 'Back to List', list_path(@list) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Lists</h1>

<div>
  <% @lists.each do |list| %>
    <div>
      <%= link_to list_path(list) do %>
      <%= list.name %>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to 'Add a new List', new_list_path %>

app/views/lists/new.html.erb
<%# <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1"> %>
      <h1>Create a new list</h1>
      <%= simple_form_for @list do |f| %>
        <%= f.input :name %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

      <%= link_to 'Back to Lists', lists_path %>
    <%# </div>
  </div>
</div> %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<h2>Movies in this list:</h2>

<% @list.movies.each do |movie| %>
  <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
  <%= image_tag movie.poster_url, alt: movie.title %>
  <li><%= movie.title %></li>
  <li><%= movie.overview %></li>
  <%# <li><%= movie.poster_url %>
  <li><%= movie.rating %></li>
<% end %>

<%= link_to "Ajouter un bookmark", new_list_bookmark_path(@list) %>

<%= link_to 'Back to Lists', lists_path %>